### ISSUE TITLE
"Casper Imaging could not locate any drives for imaging"

### ISSUE THREAD

**Issue by donmontalvo** [jamf/CasperNetInstallCreator#1]
I'm hoping this is the right place to post an issue that **@MarkPetersonURMC** reported on JAMF Nation:

https://jamfnation.jamfsoftware.com/discussion.html?id=11044

Just getting around to testing this (thanks for updating!).

I'm getting the same **Casper Imaging could not locate any drives for imaging** error when I boot into the NBI.

If I manually mount **Yadayada.nbi/Install.dmg.sparseimage** it shows up as **Volumes/Install** instead of **/Volumes/Macintosh\ HD**.

We are using **Casper NetInstall Creator 4.0 (14062401)** which we downloaded today (7/1/2014).

*Do I get a t-shirt for being the first to post an issue here? :)*

Don

**Comment by donmontalvo** [comment]
Wow I totally didn't get an alert when you responded! :) We have been trying to get this to work with Casper NetInstall Creator 5.0 and Casper Imaging 9.65 which is supposed to be able to deal with corestorage enabled drives (all Yosemite Macs ship with this), and hopefully with FV2 encrypted drives as well. Not having luck. Tried 10.10, 10.10.1, and 10.10.2 on an iMac 5K Retina.

https://jamfnation.jamfsoftware.com/discussion.html?id=13351

**Comment by donmontalvo** [comment]
FYI:

https://jamfnation.jamfsoftware.com/article.html?id=228#responseChild824

**Comment by nickamundsen** [comment]
Don,

Thanks for the note.

FYI - the bug we're dealing with is actually a Casper Imaging bug, and not
a Casper NetInstall Image Creator bug.  Casper Imaging doesn't recognize a
drive that's encrypted with FileVault.  Defect number is D-008217.  I'm
hounding engineering about it, and I will continue to do so until it is
fixed :)

Nick

**Comment by nickamundsen** [comment]
Closing since this was resolved with Casper Imaging 9.7
