### ISSUE TITLE
Setting NetInstall Image as the Default Results in 2 Defaults in Server.app

### ISSUE THREAD

**Issue by kubman007** [jamf/CasperNetInstallCreator#5]
Using Casper NetInstall Image Creator 6.0.1, we checked the option to Set This NetInstall Image as the Default Image while creating a new NetInstall.  In Server.app, version 5.0.4, there is already a netboot present and marked as default.  We assumed this option in the NetInstall Creator would override that default in Server.app and make the new NBI the default.  Once the build was complete, we opened Server.app and there are now two defaults, which should not be possible.  We were able to uncheck the old one and fix the issue, but this seems like unintended behavior.

**Comment by erikberglund** [comment]
This is working as expected, that option only sets the boolean Default to yes in NBImageInfo, and if you set that on many NetBoot sets and then copy them to your NetBoot Folder, all will look like default from the server. When you set the default form the server, it will automatically deselect every other nbi.

**Comment by nickamundsen** [comment]
Closing this issue, as we also believe that this is expected b
